### ISSUE TITLE
Sliding back the MGN9H Carriage with the provided Slide Carriage does not work from the top

### ISSUE THREAD

**Issue by realadissu** [Zev-se/Formbot-voron-2.4-build-guide#1]
In the guide.mp for Voron TAP for page 32 there is not info that the provided plastic (not printed) slide carriage is too thick to slide in the MGN9H carriage from the top. I removed the bottom screw with the added heat set and then slid it from the bottom side. Attention: Don't push to fast or you will slide out again at the top.

**Comment by SebKuzminsky** [comment]
My copy of this part is buried in my printer now, so I can't quite visualize the problem you're describing.  Can you comment in this issue and attach a picture showing the problem with the part?

**Comment by realadissu** [comment]
![IMG_7641](https://github.com/user-attachments/assets/c8485d11-8d88-4283-8560-bf6575574a94)
![IMG_7642](https://github.com/user-attachments/assets/efd4ae7a-07a7-46de-a85d-12e2321206be)
![IMG_7643](https://github.com/user-attachments/assets/9413d91a-83d0-4969-8678-a74dedc99d2a)

**Comment by SebKuzminsky** [comment]
That's excellent, thank you!  I'll add something to the guide tonight.
