### ISSUE TITLE
Split x/y endstops

### ISSUE THREAD

**Issue by pennltrex** [Zev-se/Formbot-voron-2.4-build-guide#11]
My Formbot kit, shipped Octo 31, 2024, has the x endstop switch attached directly to the toolhead (EBB SB2209 CAN documentation page 17). The Y endstop is the switch only.

![image](https://github.com/user-attachments/assets/443a827a-930c-4831-a40c-49655a05115f)
![image](https://github.com/user-attachments/assets/1ffa36e5-783c-47ad-a2c0-8f639c4af82a)

**Comment by SebKuzminsky** [comment]
Mine was the same way.  I believe the EBB SB2209 documentation describes this well.  Can you explain what issue you are reporting?

**Comment by pennltrex** [comment]
`Different versions of this kit handle X & Y endstops (limit switches) in different ways. Newer versions of the kit use SB2209 to put the X endstop on the toolhead and the Y endstop on the right-rear coreXY motor: https://www.printables.com/model/527499-voron-v24-pg7-umbilical-y-endstop-relocation-with-. The older version of the kit mounts the limit switches in a different way than mainline Voron:`

I read the above and click the link, but I think what would make it clearer would be to include the page number of the EBB SB2209 documentation. I found it easy to miss.

**Comment by pennltrex** [comment]
Also, you've included photos of two of the three possibilities.

**Comment by SebKuzminsky** [comment]
Hmm, yes i see what you mean, the wording of that is pretty awkward and confusing, i'll try to clarify.

Your first picture shows your Y endstop mounted on the "XY Endstop Board" which mounts on the right-hand side of the gantry.  This is wrong: when using the 2209 the Y endstop should go on the coreXY motor mount.

Your second picture shows your X endstop correctly mounted to the toolhead.

I started to update the X/Y endstop info a bit, can you take a look and see if it's clearer?  <https://github.com/Zev-se/Formbot-voron-2.4-build-guide/blob/xy-endstops/guide.md>
* I added your X endstop picture to the "EBB SB2209, page 16" section, thanks!
* I reworded the Y endstop info in the "2.4, page 162" section to hopefully be more clear.

After you relocate your Y endstop to the coreXY motor mount, please post a picture of it here and i'll add that to the guide too.

Thank you for raising this issue and for the pictures.

**Comment by pennltrex** [comment]
Formbot has an STL with a mount for the y-endstop that my PIF provider didn't supply, so I've superglued the switch in the place where it would be. It seems like this will work for now. I'll print a new A Drive Frame Upper when I get it done, and take some photos.
[STL/Primary/a_drive_frame_upper_with_jst_y_endstop.stl](https://github.com/FORMBOT/Voron-2.4/blob/main/STL/Primary/a_drive_frame_upper_with_jst_y_endstop.stl)

![image](https://github.com/user-attachments/assets/c265679e-e989-4713-a997-5d07645a5be4)

**Comment by drake7707** [comment]
I had the same issue and just screwed it into the bare plastic with the self tapping screws. Seemed to work alright

**Comment by SebKuzminsky** [comment]
I pushed the changes i proposed above, hopefully this makes things more clear.  Please open a PR or another issue if you notice other areas that can be improved.
