### ISSUE TITLE
Option to use magnets TAP p27

### ISSUE THREAD

**Issue by drake7707** [Zev-se/Formbot-voron-2.4-build-guide#2]
It might be worth calling out in the guide that with RC8 there's the option to use magnets in the TAP front. I initially just followed the guide and installed M3x6 FHCS but once assembled I barely got any magnetic force to return TAP to its original position when pushed up. The magnets in the kit are fine, I could hang my hex key from them but the screws from the kit are barely magnetic and could not overcome the friction that the linear rail introduced.

Once I added magnets in the holes (and ensured the polarity is correct) TAP works so much better, it correctly returned back to its lower position even with the belts tucked in there.

Edit: just read through the feedback page and there it's mentioned. I would add it to the guide as well.

**Comment by SebKuzminsky** [comment]
Hi Sarah, thank you for the suggestion.  How's this look:  https://github.com/Zev-se/Formbot-voron-2.4-build-guide/blob/tap-magnets/guide.md

**Comment by drake7707** [comment]
Great, thanks!
